export default {
  CHANGE_CITY: `CHANGE_CITY`,
  RESET_CITY: `RESET_CITY`,
  GET_ACTIVE_OFFER: `GET_ACTIVE_OFFER`,
  GET_ACTIVE_SORT: `GET_ACTIVE_SORT`,
  REQUIRED_AUTHORIZATION: `REQUIRED_AUTHORIZATION`,
  LOAD_OFFERS: `LOAD_OFFERS`,
  LOAD_NEARBY_OFFERS: `LOAD_NEARBY_OFFERS`,
  LOAD_OFFER: `LOAD_OFFER`,
  SHOW_ERROR: `SHOW_ERROR`,
  LOAD_COMMENTS: `LOAD_COMMENTS`,
  ADD_EMAIL: `ADD_EMAIL`,
  LOAD_FAVORITE_OFFERS: `LOAD_FAVORITE_OFFERS`,
};

