export default {
  CHANGE_CITY: `CHANGE_CITY`,
  RESET_CITY: `RESET_CITY`,
  GET_ACTIVE_OFFER: `GET_ACTIVE_OFFER`,
  GET_ACTIVE_SORT: `GET_ACTIVE_SORT`,
  REQUIRED_AUTHORIZATION: `REQUIRED_AUTHORIZATION`,
  LOAD_OFFERS: `LOAD_OFFERS`,
  SHOW_ERROR: `SHOW_ERROR`,
};

